spring:
  config:
    activate:
      on-profile: mysql
  datasource:
    url: jdbc:mysql://localhost:3306/customerDatabase
    username: root
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  enabled: true
  spring-test:
    vehicles:
      maxNoOfVehicles: 20
      enabled: true
    customers:
      maxNoOfCustomers: 20
      enabled: true

---

spring:
  config:
    activate:
      on-profile: h2
  h2:
    console:
      enabled: true
  datasource:
    generate-unique-name: false
    name: myDatabaseNew
  enabled: true
  jpa:
    properties:
      javax:
        persistence:
          validation:
            mode: none
  spring-test:
    vehicles:
      maxNoOfVehicles: 20
      enabled: true
    customers:
      maxNoOfCustomers: 20
      enabled: true

server:
    port: 8084

---
logging:
  level:
    com:
      zaxxer:
        hikari: TRACE
